In [3]:
import pandas as pd
import os

In [4]:
path = "/Users/andreasnilsson/Library/CloudStorage/OneDrive-Nstart/Skrivbordet/Repository Homes/Behavior_Scorecard-DATA-223/1. Data"
os.chdir(path)

In [7]:
file_path = './base1.xlsx'

In [14]:
# Read a specific sheet by name
Resultat = pd.read_excel(file_path, sheet_name='Resultat')
both = pd.read_excel(file_path, sheet_name='b√•da')

# Setting options to display all columns
pd.set_option('display.max_columns', None)

In [17]:
Resultat = Resultat.sort_values(by='AccountNumber')

In [18]:
both = both.sort_values(by='AccountNumber')

In [20]:
Resultat

,AccountNumber,RiskStage,RiskClass,Ord,Date,Base,ContractualInterest,ContractualAmort,InterestIncomeByEIR,CashFlowsNPV,AmortizedCostBOP,AmortizedCostEOP,EIR,EIRmth,Annuity,StartupFee,AcquisitionCost,StartupFeeLeft,AcquisitionCostLeft,StartupFeeAmort,AcquisitionCostAmort,OriginalTenor,RemainingTenor,DisbursedDate,InterestRate,ModelMonths,AFS,InvoicedNotPaid,FundingCompany,SurvivalRate,LGD,EAD,MPD,LPD,ECL,ECLNPV,CashFlowsRC,CashFlowsNPVRC,MOB,DefaultDate,MonthsSinceDefault,SpecialCase
3476,5000054,1.0,NaN,0,2023-12-31,177192.91,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,895,10045.000000,895,10045.000000,0,0,144,45,2015-09-16,0.2865,36,0,0.00,Erik Penser Bank AB,0.999271,0.3902,NaN,NaN,NaN,NaN,NaN,NaN,NaN,99,NaT,NaN,NaN
1652,5000161,3.0,NaN,0,2023-12-31,212983.95,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,895,10150.000000,895,10150.000000,0,0,144,77,2015-09-28,0.2965,180,0,0.00,Nystart Finans Sverige AB,NaN,0.3000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,99,2021-04-13,32.0,NaN
2054,5000179,3.0,NaN,0,2023-12-31,194394.86,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,895,11375.000000,895,11375.000000,0,0,144,73,2015-09-28,0.1865,180,0,0.00,Nystart Finans Sverige AB,NaN,0.3000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,99,2021-08-13,28.0,NaN
1653,5000187,3.0,NaN,0,2023-12-31,328236.44,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,895,12250.000000,895,12250.000000,0,0,144,106,2015-10-09,0.2665,180,0,25534.29,Nystart Finans Sverige AB,NaN,0.3000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,98,2018-12-03,60.0,NaN
2055,5000229,3.0,NaN,0,2023-12-31,240011.11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,895,9800.000000,895,9800.000000,0,0,144,74,2015-10-09,0.2765,180,0,24711.20,Nystart Finans Sverige AB,NaN,0.3000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,98,2021-07-13,29.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1313,7988900,1.0,NaN,0,2023-12-31,150000.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,995,7500.000000,995,7500.000000,0,0,120,120,2023-12-29,0.2210,36,0,0.00,Erik Penser Bank AB,0.997540,0.3902,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaT,NaN,NaN
6917,7989205,1.0,NaN,0,2023-12-31,190000.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,995,9500.000000,995,9500.000000,0,0,144,144,2023-12-29,0.2595,36,0,0.00,Erik Penser Bank AB,0.995686,0.3902,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaT,NaN,NaN
6918,7989437,1.0,NaN,0,2023-12-31,44115.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1995,2946.776746,1995,2946.776746,0,0,96,96,2023-12-28,0.1880,36,0,0.00,Erik Penser Bank AB,0.995228,0.3902,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaT,NaN,NaN
1314,7989791,1.0,NaN,0,2023-12-31,85000.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,995,4250.000000,995,4250.000000,0,0,36,36,2023-12-29,0.2795,36,0,0.00,Erik Penser Bank AB,0.994339,0.3902,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaT,NaN,NaN
6919,7990179,1.0,NaN,0,2023-12-31,150000.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1995,9822.589154,1995,9822.589154,0,0,96,96,2023-12-29,0.2110,36,0,0.00,Erik Penser Bank AB,0.995293,0.3902,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaT,NaN,NaN

In [21]:
both

,AccountNumber,RiskStage,RiskClass,Ord,Date,CurrentAmount,ContractualInterest,ContractualAmort,InterestIncomeByEIR,CashFlowsNPV,AmortizedCostBOP,AmortizedCostEOP,EIR,EIRmth,Annuity,StartupFee,AcquisitionCost,StartupFeeLeft,AcquisitionCostLeft,StartupFeeAmort,AcquisitionCostAmort,OriginalTenor,RemainingTenor,DisbursedDate,InterestRate,ModelMonths,AFS,InvoicedNotPaid,FundingCompany,SurvivalRate,LGD,EAD,MPD,LPD,ECL,ECLNPV,CashFlowsRC,CashFlowsNPVRC,MOB,DefaultDate,MonthsSinceDefault,SpecialCase
5291,5000054,1.0,NaN,0,2023-12-31,177192.91,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,895,10045.000000,895,10045.000000,0,0,144,45,2015-09-16,0.2865,36,0,0.00,Erik Penser Bank AB,0.999271,0.3902,NaN,NaN,NaN,NaN,NaN,NaN,NaN,99,NaT,NaN,NaN
5091,5000161,3.0,NaN,0,2023-12-31,212983.95,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,895,10150.000000,895,10150.000000,0,0,144,77,2015-09-28,0.2965,180,0,0.00,Nystart Finans Sverige AB,NaN,0.3000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,99,2021-04-13,32.0,NaN
3374,5000179,3.0,NaN,0,2023-12-31,194394.86,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,895,11375.000000,895,11375.000000,0,0,144,73,2015-09-28,0.1865,180,0,0.00,Nystart Finans Sverige AB,NaN,0.3000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,99,2021-08-13,28.0,NaN
5092,5000187,3.0,NaN,0,2023-12-31,328236.44,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,895,12250.000000,895,12250.000000,0,0,144,106,2015-10-09,0.2665,180,0,25534.29,Nystart Finans Sverige AB,NaN,0.3000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,98,2018-12-03,60.0,NaN
3375,5000229,3.0,NaN,0,2023-12-31,240011.11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,895,9800.000000,895,9800.000000,0,0,144,74,2015-10-09,0.2765,180,0,24711.20,Nystart Finans Sverige AB,NaN,0.3000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,98,2021-07-13,29.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5089,7988900,1.0,NaN,0,2023-12-31,150000.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,995,7500.000000,995,7500.000000,0,0,120,120,2023-12-29,0.2210,36,0,0.00,Erik Penser Bank AB,0.997540,0.3902,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaT,NaN,NaN
1482,7989205,1.0,NaN,0,2023-12-31,190000.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,995,9500.000000,995,9500.000000,0,0,144,144,2023-12-29,0.2595,36,0,0.00,Erik Penser Bank AB,0.995686,0.3902,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaT,NaN,NaN
1483,7989437,1.0,NaN,0,2023-12-31,44115.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1995,2946.776746,1995,2946.776746,0,0,96,96,2023-12-28,0.1880,36,0,0.00,Erik Penser Bank AB,0.995228,0.3902,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaT,NaN,NaN
5090,7989791,1.0,NaN,0,2023-12-31,85000.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,995,4250.000000,995,4250.000000,0,0,36,36,2023-12-29,0.2795,36,0,0.00,Erik Penser Bank AB,0.994339,0.3902,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaT,NaN,NaN
1484,7990179,1.0,NaN,0,2023-12-31,150000.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1995,9822.589154,1995,9822.589154,0,0,96,96,2023-12-29,0.2110,36,0,0.00,Erik Penser Bank AB,0.995293,0.3902,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaT,NaN,NaN

False

In [32]:
Resultat = Resultat.rename(columns={'Base':'CurrentAmount'})

Resultat

,AccountNumber,RiskStage,RiskClass,Ord,Date,CurrentAmount,ContractualInterest,ContractualAmort,InterestIncomeByEIR,CashFlowsNPV,AmortizedCostBOP,AmortizedCostEOP,EIR,EIRmth,Annuity,StartupFee,AcquisitionCost,StartupFeeLeft,AcquisitionCostLeft,StartupFeeAmort,AcquisitionCostAmort,OriginalTenor,RemainingTenor,DisbursedDate,InterestRate,ModelMonths,AFS,InvoicedNotPaid,FundingCompany,SurvivalRate,LGD,EAD,MPD,LPD,ECL,ECLNPV,CashFlowsRC,CashFlowsNPVRC,MOB,DefaultDate,MonthsSinceDefault,SpecialCase
3476,5000054,1.0,NaN,0,2023-12-31,177192.91,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,895,10045.000000,895,10045.000000,0,0,144,45,2015-09-16,0.2865,36,0,0.00,Erik Penser Bank AB,0.999271,0.3902,NaN,NaN,NaN,NaN,NaN,NaN,NaN,99,NaT,NaN,NaN
1652,5000161,3.0,NaN,0,2023-12-31,212983.95,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,895,10150.000000,895,10150.000000,0,0,144,77,2015-09-28,0.2965,180,0,0.00,Nystart Finans Sverige AB,NaN,0.3000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,99,2021-04-13,32.0,NaN
2054,5000179,3.0,NaN,0,2023-12-31,194394.86,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,895,11375.000000,895,11375.000000,0,0,144,73,2015-09-28,0.1865,180,0,0.00,Nystart Finans Sverige AB,NaN,0.3000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,99,2021-08-13,28.0,NaN
1653,5000187,3.0,NaN,0,2023-12-31,328236.44,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,895,12250.000000,895,12250.000000,0,0,144,106,2015-10-09,0.2665,180,0,25534.29,Nystart Finans Sverige AB,NaN,0.3000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,98,2018-12-03,60.0,NaN
2055,5000229,3.0,NaN,0,2023-12-31,240011.11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,895,9800.000000,895,9800.000000,0,0,144,74,2015-10-09,0.2765,180,0,24711.20,Nystart Finans Sverige AB,NaN,0.3000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,98,2021-07-13,29.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1313,7988900,1.0,NaN,0,2023-12-31,150000.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,995,7500.000000,995,7500.000000,0,0,120,120,2023-12-29,0.2210,36,0,0.00,Erik Penser Bank AB,0.997540,0.3902,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaT,NaN,NaN
6917,7989205,1.0,NaN,0,2023-12-31,190000.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,995,9500.000000,995,9500.000000,0,0,144,144,2023-12-29,0.2595,36,0,0.00,Erik Penser Bank AB,0.995686,0.3902,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaT,NaN,NaN
6918,7989437,1.0,NaN,0,2023-12-31,44115.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1995,2946.776746,1995,2946.776746,0,0,96,96,2023-12-28,0.1880,36,0,0.00,Erik Penser Bank AB,0.995228,0.3902,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaT,NaN,NaN
1314,7989791,1.0,NaN,0,2023-12-31,85000.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,995,4250.000000,995,4250.000000,0,0,36,36,2023-12-29,0.2795,36,0,0.00,Erik Penser Bank AB,0.994339,0.3902,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaT,NaN,NaN
6919,7990179,1.0,NaN,0,2023-12-31,150000.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1995,9822.589154,1995,9822.589154,0,0,96,96,2023-12-29,0.2110,36,0,0.00,Erik Penser Bank AB,0.995293,0.3902,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaT,NaN,NaN

In [36]:
set(Resultat.EAD)

{nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 ...}

In [41]:
df1 = Resultat.fillna(0).copy()
df2 = both.fillna(0).copy()

In [42]:
 
for col in df1.columns:

    print(col)
    print(df1[col].iloc[0] == df2[col].iloc[0] )
    print()

AccountNumber
True

RiskStage
True

RiskClass
True

Ord
True

Date
True

CurrentAmount
True

ContractualInterest
True

ContractualAmort
True

InterestIncomeByEIR
True

CashFlowsNPV
True

AmortizedCostBOP
True

AmortizedCostEOP
True

EIR
True

EIRmth
True

Annuity
True

StartupFee
True

AcquisitionCost
True

StartupFeeLeft
True

AcquisitionCostLeft
True

StartupFeeAmort
True

AcquisitionCostAmort
True

OriginalTenor
True

RemainingTenor
True

DisbursedDate
True

InterestRate
True

ModelMonths
True

AFS
True

InvoicedNotPaid
True

FundingCompany
True

SurvivalRate
True

LGD
True

EAD
True

MPD
True

LPD
True

ECL
True

ECLNPV
True

CashFlowsRC
True

CashFlowsNPVRC
True

MOB
True

DefaultDate
True

MonthsSinceDefault
True

SpecialCase
True

In [43]:
df1.equals(df2)

False

In [44]:
def fn_amortize(base, amount, m):
    i = 1
    amort = 0.0
    while i <= m:
        amort += (amount - amort) * (1.0 / base)
        i += 1

        print(amort)

    return round(amort, 2)

# Example usage:
base = 36
amount = 1000.00  # Example amount
m = 12  # Example period

amortized_value = fn_amortize(base, amount, m)
print(amortized_value)

27.777777777777775
54.78395061728395
81.03995198902606
106.56661998933089
131.38421387851614
155.51243015966847
178.97041821078878
201.77679548271132
223.9496622748582
245.50661610055658
266.4647656533189
286.84074438517115
286.84